update tor

diff --git a/security/tor/files/tor.in b/security/tor/files/tor.in
--- a/security/tor/files/tor.in
+++ b/security/tor/files/tor.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: head/security/tor/files/tor.in 425102 2016-11-02 02:57:03Z jbeich $
+# $FreeBSD: head/security/tor/files/tor.in 463489 2018-03-03 16:00:48Z yuri $
 #
 # PROVIDE: tor
 # REQUIRE: DAEMON FILESYSTEMS
@@ -21,6 +21,7 @@
 # tor_disable_default_instance (str):	Doesn't run the default instance.
 #			Only valid when tor_instances is used.
 #			Default: NO
+# tor_setuid (str):	Runtime setuid.  Default: NO
 #
 # The instance definition that tor_instances expects:
 # inst_name{:inst_conf:inst_user:inst_group:inst_pidfile:inst_data_dir}
@@ -30,6 +31,7 @@
 
 name="tor"
 rcvar=tor_enable
+exit_code=0
 
 load_rc_config ${name}
 
@@ -41,14 +43,16 @@ load_rc_config ${name}
 : ${tor_pidfile="/var/run/tor/tor.pid"}
 : ${tor_datadir="/var/db/tor"}
 : ${tor_disable_default_instance="NO"}
+: ${tor_setuid="NO"}
 
-instance=${2}
+instance=${slave_instance}
 if [ -n "${instance}" ]; then
-  # extended instance: parameters are set explicitly
   inst_def=${instance}
   inst_name=${inst_def%%:*}
+  [ "${inst_name}" != "main" ] || err 1 "${name} instance can't be named 'main'"
   inst_def=${inst_def#$inst_name}
   if [ -n "$inst_def" ]; then
+    # extended instance: parameters are set explicitly
     inst_def=${inst_def#:}
     tor_conf=${inst_def%%:*}
     inst_def=${inst_def#$tor_conf:}
@@ -59,7 +63,7 @@ if [ -n "${instance}" ]; then
     tor_pidfile=${inst_def%%:*}
     tor_datadir=${inst_def#$tor_pidfile:}
     if [ -z "${tor_conf}" -o -z "${tor_user}" -o -z "${tor_group}" -o -z "${tor_pidfile}" -o -z "${tor_datadir}" ]; then
-      warn "invalid tor instance ${inst_name} settings"
+      warn "invalid tor instance ${inst_name} settings: ${instance}"
       exit 1
     fi
   else
@@ -82,10 +86,25 @@ if [ -n "${instance}" ]; then
 fi
 
 if [ -z "${instance}" -a -n "${tor_instances}" ]; then
+  inst_only="$2"
+  inst_done=0
   for i in ${tor_instances}; do
-    %%PREFIX%%/etc/rc.d/tor $1 ${i} || warn "$1 failed for the tor instance $i"
+    inst_name=${i%%:*}
+    if [ -z "${inst_only}" -o "${inst_name}" = "${inst_only}" ]; then
+      echo -n "${name} instance ${inst_name}: "
+      if ! slave_instance=${i} %%PREFIX%%/etc/rc.d/tor "$1"; then
+        exit_code=1
+      fi
+      inst_done=$((inst_done+1))
+    fi
   done
-  checkyesno tor_disable_default_instance && return 0
+  if [ -z "${inst_only}" -o "${inst_only}" = "main" ]; then
+    checkyesno tor_disable_default_instance && return $exit_code
+    echo -n "${name} main instance: "
+  elif [ -n "${inst_only}" ]; then
+    [ $inst_done -gt 0 ] || err 1 "${name} instance '$inst_only' isn't defined"
+    return  $exit_code
+  fi
 fi
 
 required_files=${tor_conf}
@@ -95,5 +114,19 @@ command="%%PREFIX%%/bin/${name}"
 command_args="-f ${tor_conf} --PidFile ${tor_pidfile} --RunAsDaemon 1 --DataDirectory ${tor_datadir}"
 extra_commands="reload"
 
-run_rc_command "$1"
+# clear user setting in conf file: it should be done through the command line
+if grep -q "^User ${tor_user}$" ${tor_conf}; then
+  sed -i '' -e "s/^User ${tor_user}$//" ${tor_conf}
+fi
 
+if [ $tor_setuid = "YES" ]; then
+  command_args="${command_args} --User ${tor_user}"
+  tor_user="root"
+  tor_group="wheel"
+fi
+
+if ! run_rc_command "$1"; then
+  exit_code=1
+fi
+
+return $exit_code
