update to 1.7.1

diff --git a/devel/doxygen/files/patch-configure b/devel/doxygen/files/patch-configure
--- a/devel/doxygen/files/patch-configure
+++ b/devel/doxygen/files/patch-configure
@@ -1,45 +1,54 @@
---- configure.orig	Sat May 17 13:51:10 2008
-+++ configure	Thu Aug 14 10:15:56 2008
-@@ -179,6 +179,12 @@
-         f_insttool=/usr/bin/install
+--- configure.orig	2010-06-15 04:00:19.000000000 -0400
++++ configure	2010-06-15 07:48:37.000000000 -0400
+@@ -269,7 +269,7 @@
+     echo "  QTDIR environment variable not set!"
+     echo -n "  Checking for Qt..."
+     for d in /usr/{lib,share,qt}/{qt-4,qt4,qt,qt*,4} /usr; do
+-      if test -x "$d/bin/qmake"; then
++      if test -x "$d/bin/qmake-qt4"; then
+         QTDIR=$d
        fi
-       ;;
-+   MidnightBSD:*)
-+      f_platform=freebsd-g++
-+      if test "$f_insttool" = NO; then
-+        f_insttool=/usr/bin/install
-+      fi
-+      ;;
-     HP-UX:*)
-       f_platform=hpux-g++
-       if test "$f_insttool" = NO; then
-@@ -596,7 +602,7 @@
+     done
+@@ -280,7 +280,7 @@
+   if test -z "$QTDIR"; then
+     echo "QTDIR not set and Qt not found at standard locations!"
+     echo
+-    echo "Set the QTDIR environment variable such that \$QTDIR/bin/qmake exists."
++    echo "Set the QTDIR environment variable such that \$QTDIR/bin/qmake-qt4 exists."
+     echo "check the Qt installation instructions!"
+     exit 2
+   fi
+@@ -576,7 +576,7 @@
+ fi
+ if test "$f_wizard" = YES; then
+   cat >> .tmakeconfig <<EOF
+-TMAKE_MOC = $QTDIR/bin/moc
++TMAKE_MOC = $QTDIR/bin/moc-qt4
  EOF
  fi
  
--f_inmakefiles="Makefile.in qtools/Makefile.in src/Makefile.in examples/Makefile.in doc/Makefile.in addon/doxywizard/Makefile.in addon/doxmlparser/src/Makefile.in addon/doxmlparser/test/Makefile.in addon/doxmlparser/examples/metrics/Makefile.in libpng/Makefile.in libmd5/Makefile.in addon/doxyapp/Makefile.in"
+@@ -586,7 +586,7 @@
+ EOF
+ fi
+ 
+-f_inmakefiles="Makefile.in qtools/Makefile.in src/Makefile.in examples/Makefile.in doc/Makefile.in addon/doxywizard/Makefile.in addon/doxmlparser/src/Makefile.in addon/doxmlparser/test/Makefile.in addon/doxmlparser/examples/metrics/Makefile.in libmd5/Makefile.in addon/doxyapp/Makefile.in"
 +f_inmakefiles="Makefile.in qtools/Makefile.in src/Makefile.in examples/Makefile.in doc/Makefile.in addon/doxywizard/Makefile.in addon/doxmlparser/src/Makefile.in addon/doxmlparser/test/Makefile.in addon/doxmlparser/examples/metrics/Makefile.in addon/doxyapp/Makefile.in"
  
  for i in $f_inmakefiles ; do
       SRC=$i
-@@ -612,10 +618,8 @@
-      if test $i = Makefile.in; then
+@@ -603,7 +603,6 @@
         echo "" >> $DST
         echo "all: src/version.cpp " >> $DST
--       echo "	\$(MAKE) -C qtools" >> $DST
--       echo "	\$(MAKE) -C libpng" >> $DST
+        echo "	\$(MAKE) -C qtools" >> $DST
 -       echo "	\$(MAKE) -C libmd5" >> $DST
--       echo "	\$(MAKE) -C src" >> $DST
-+       echo "	\$(MAKE) -j2 -C qtools" >> $DST
-+       echo "	\$(MAKE) -j2 -C src" >> $DST
+        echo "	\$(MAKE) -C src" >> $DST
         if test $f_wizard = YES; then
           echo "	\$(MAKE) -C addon/doxywizard" >> $DST
-        fi
-@@ -637,7 +641,7 @@
+@@ -626,7 +625,7 @@
       echo "  Created $DST from $SRC..."
  done
  
--f_inprofiles="qtools/qtools.pro.in src/libdoxygen.pro.in src/libdoxycfg.pro.in src/doxygen.pro.in src/doxytag.pro.in addon/doxywizard/doxywizard.pro.in addon/doxmlparser/src/doxmlparser.pro.in addon/doxmlparser/test/xmlparse.pro.in addon/doxmlparser/examples/metrics/metrics.pro.in libpng/libpng.pro.in libmd5/libmd5.pro.in addon/doxyapp/doxyapp.pro.in" 
+-f_inprofiles="qtools/qtools.pro.in src/libdoxygen.pro.in src/libdoxycfg.pro.in src/doxygen.pro.in src/doxytag.pro.in addon/doxywizard/doxywizard.pro.in addon/doxmlparser/src/doxmlparser.pro.in addon/doxmlparser/test/xmlparse.pro.in addon/doxmlparser/examples/metrics/metrics.pro.in libmd5/libmd5.pro.in addon/doxyapp/doxyapp.pro.in" 
 +f_inprofiles="qtools/qtools.pro.in src/libdoxygen.pro.in src/libdoxycfg.pro.in src/doxygen.pro.in src/doxytag.pro.in addon/doxywizard/doxywizard.pro.in addon/doxmlparser/src/doxmlparser.pro.in addon/doxmlparser/test/xmlparse.pro.in addon/doxmlparser/examples/metrics/metrics.pro.in addon/doxyapp/doxyapp.pro.in" 
  
  for i in $f_inprofiles ; do
