5.41

diff --git a/sysutils/smartmontools/files/smart.in b/sysutils/smartmontools/files/smart.in
--- a/sysutils/smartmontools/files/smart.in
+++ b/sysutils/smartmontools/files/smart.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 # This script is in the public domain.  Original author: Garrett Wollman
 #
-# $FreeBSD: ports/sysutils/smartmontools/files/smart.in,v 1.5 2009/06/03 18:12:30 wxs Exp $
+# $FreeBSD: ports/sysutils/smartmontools/files/smart.in,v 1.11 2011/07/22 06:38:53 sunpoet Exp $
 #
 
 if [ -r /etc/defaults/periodic.conf ]; then
@@ -29,32 +29,58 @@ fi
 
 trim_junk="tail -n +4"
 
-tmpfile="$(mktemp /var/run/daily.XXXXXXXX)"
+tmpfile="$(mktemp -t daily)"
 trap "rm -f ${tmpfile}" 0 1 3 15
 
 rc=0
 case "${daily_status_smart_enable}" in
 	[Yy][Ee][Ss])
+		echo
+		echo 'SMART status:'
 		cd /dev
 		for device in ${daily_status_smart_devices}; do
+			device="${device#/dev/}"
+			devflags=""
+			case ${device} in
+			cd*) ;;
+			tw[ae]*) devflags="-d3ware,${device##tw[ae][0-9]*,}"
+				device="/dev/${device%,[0-9]*}"
+				;;
+			ciss*)  devflags="-dcciss,${device##ciss[0-9]*,}"
+				device="/dev/${device%,[0-9]*}"
+				;;
+			/*)	;;
+			*)	device="/dev/${device}"
+			        ;;
+			esac
+
 			if [ -e ${device} ]; then
-				echo 
-				echo "Checking health of ${device}:"
-				echo
-				${smartctl} ${daily_status_smartctl_flags} ${device} > "${tmpfile}"
+				echo -n "Checking health of ${device}"
+				if [ -n "${devflags}" ]; then
+					echo -n " (${devflags})"
+				fi
+				echo -n ": "
+
+				${smartctl} ${devflags} ${daily_status_smartctl_flags} ${device} > "${tmpfile}"
 				status=$?
-				if [ $((status & 3)) -ne 0 ]; then
+				if [ ${status} -eq 0 ]; then
+					echo "OK"
+				elif [ ${status} -eq 32 ]; then
+					echo "OK (but has failed in the past)"
+				elif [ $((status & 3)) -ne 0 ]; then
 					rc=2
 					${trim_junk} "${tmpfile}"
-				elif [ $status -ne 0 ]; then
-					rc=1
-					${smartctl} ${daily_status_smartctl_extra_status_flags} ${device} | ${trim_junk}
+				elif [ `grep -c '^SMART support is: Unavailable' ${tmpfile}` -eq 1 ] ; then
+					rc=2
+				echo "N/A"
 				else
-					${trim_junk} "${tmpfile}"
+					rc=1
+					${smartctl} ${devflags} ${daily_status_smartctl_extra_status_flags} \
+						${device} | ${trim_junk}
 				fi
 			fi
 		done
 		;;
 esac
 
-exit "$rc"
+exit "${rc}"
