add  winscp options

diff --git a/shells/scponly/files/scponlyc.in b/shells/scponly/files/scponlyc.in
--- a/shells/scponly/files/scponlyc.in
+++ b/shells/scponly/files/scponlyc.in
@@ -7,12 +7,12 @@
 # KEYWORD: shutdown
 
 # Add the following lines to /etc/rc.conf to enable scponly:
-# spconlyc_enable (bool):		Set to "NO" by default.
+# scponlyc_enable (bool):		Set to "NO" by default.
 #					Set it to "YES" to enable scponly
 # scponlyc_shells (str):		Set to "/etc/shells" by default.
 # scponlyc_passwd (str):		Set to "/etc/passwd" by default.
 
-. %%RC_SUBR%%
+. /etc/rc.subr
 
 scponlyc_shells="${scponlyc_shells:-/etc/shells}"
 scponlyc_passwd="${scponlyc_passwd:-/etc/passwd}"
@@ -32,12 +32,15 @@ make_devfs() {
 	# devfs created. If ~/dev exists, it will be deleted.
 
 	eval DEV="~$1/dev"
-	while /sbin/umount "${DEV}" 2>/dev/null; do :; done
-	/bin/rm -rf "${DEV}"
+	if /sbin/mount | grep "${DEV}" >/dev/null 2>&1; then
+		/sbin/umount "${DEV}" 2>/dev/null
+	fi
+	/bin/rmdir "${DEV}" || err 1 "Unable to remove $DEV"
 	/bin/mkdir -p "${DEV}"
-	if /sbin/mount -t devfs dev "${DEV}"; then
-		/sbin/devfs -m "${DEV}" rule -s 1 applyset && \
-		/sbin/devfs -m "${DEV}" rule -s 2 applyset || \
+	devfs_domount "${DEV}"
+	if devfs_init_rulesets; then
+		devfs_apply_ruleset "devfsrules_hide_all" "${DEV}" && \
+		devfs_apply_ruleset "devfsrules_unhide_basic" "${DEV}" || \
 		/sbin/umount "${DEV}" 2>/dev/null
 	fi
 }
