Update to 0.93.  fix cve-2008-1837

diff --git a/security/clamav/files/clamav-clamd.in b/security/clamav/files/clamav-clamd.in
--- a/security/clamav/files/clamav-clamd.in
+++ b/security/clamav/files/clamav-clamd.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: ports/security/clamav/files/clamav-clamd.in,v 1.1 2006/04/06 15:20:18 garga Exp $
+# $FreeBSD: ports/security/clamav/files/clamav-clamd.in,v 1.2 2008/04/16 16:05:54 garga Exp $
 # $MidnightBSD$
 
 # PROVIDE: clamd
@@ -31,5 +31,15 @@ load_rc_config "$name"
 : ${clamav_clamd_enable="NO"}
 : ${clamav_clamd_flags=""}
 : ${clamav_clamd_socket="%%CLAMAV_CLAMD_SOCKET%%"}
+
+start_precmd=clamav_clamd_precmd
+
+#clamav .93 won't start without a valid main.cvd file
+clamav_clamd_precmd() {
+	if [ ! -f %%DBDIR%%/main.cvd ];then
+		echo "Missing %%DBDIR%%/clamav/*.cvd files.  You must run freshclam first"
+		exit 1
+	fi
+}
 
 run_rc_command "$1"
