update to 7.x

diff --git a/net/boinc-client/files/pkg-install.in b/net/boinc-client/files/pkg-install.in
--- a/net/boinc-client/files/pkg-install.in
+++ b/net/boinc-client/files/pkg-install.in
@@ -1,25 +1,39 @@
 #!/bin/sh
+#
+# $MidnightBSD:$
+#
 
-username=%%BOINC_USER%%
-group=%%BOINC_GROUP%%
-home=%%BOINC_HOME%%
+PATH=/bin:/usr/sbin:/usr/bin:/usr/sbin
+
+user=%%BOINC_CLIENT_USER%%
+group=%%BOINC_CLIENT_GROUP%%
+home="%%BOINC_CLIENT_HOME%%"
 shell=/bin/sh
 
 case $2 in
-POST-INSTALL)
-    if ! pw usershow ${username} >/dev/null 2>&1; then
-	if ! pw useradd ${username} -g ${group} -c BOINC -d ${home} -s ${shell}; then
-		err=$?
-		echo "WARNING: Unable to create user.  pw returned $err"
-		echo "You will need to create a boinc user and chown the boinc dir."
-		exit $err
+PRE-INSTALL)
+	if ! pw usershow ${user} 2>/dev/null 1>&2; then
+		if ! pw useradd ${user} -g ${group} -c "BOINC client user" \
+		    -d "${home}" -s ${shell}; then
+			echo "Failed to create user \"${user}\"." >&2
+			exit 1
+		else
+			echo "User \"${user}\" created successfully:"
+		fi
 	else
-		echo "boinc user created."
+		echo "Using existent user \"${user}\":"
 	fi
-    else
-	echo "boinc user found.  using existing boinc user."
-    fi
-    mkdir -p ${home} ${home}/projects
-    chown ${username}:${group} ${home} ${home}/projects
-    ;;
+	pw usershow ${user}
+	mkdir -m u=rwx,go= -p "${home}"
+	if [ ! -e "${home}/skins" -a ! -L "${home}/skins" ]; then
+		ln -s "%%PREFIX%%/share/boinc/skins" "${home}/skins"
+	fi
+	if [ ! -e "${home}/ca-bundle.crt" -a ! -L "${home}/ca-bundle.crt" ]; then
+		ln -s "%%LOCALBASE%%/share/certs/ca-root-nss.crt" "${home}/ca-bundle.crt"
+	fi
+	echo "Adjusting file ownership in \"${home}\" to ${user}:${group}"
+	chown -hR ${user}:${group} "${home}"
+	;;
 esac
+
+exit 0
