devel/tcl-trf: oof

diff --git a/devel/tcl-trf/files/patch-configure b/devel/tcl-trf/files/patch-configure
--- a/devel/tcl-trf/files/patch-configure
+++ b/devel/tcl-trf/files/patch-configure
@@ -1,23 +1,63 @@
---- configure	2009-06-18 00:45:24.000000000 -0400
-+++ configure	2009-07-12 20:45:07.000000000 -0400
-@@ -6752,5 +6752,5 @@
+--- configure.orig	2025-01-02 14:08:29.772283000 -0500
++++ configure	2025-01-02 14:08:57.344197000 -0500
+@@ -7114,6 +7114,42 @@
  
  
--    vars="zlib.c bz2lib.c loadman.c init.c registry.c unstack.c load.c crypt.c"
-+    vars="init.c registry.c unstack.c load.c crypt.c"
+ 
++    vars="md2d.c"
++    for i in $vars; do
++	case $i in
++	    \$*)
++		# allow $-var names
++		PKG_SOURCES="$PKG_SOURCES $i"
++		PKG_OBJECTS="$PKG_OBJECTS $i"
++		;;
++	    *)
++		# check for existence - allows for generic/win/unix VPATH
++		# To add more dirs here (like 'src'), you have to update VPATH
++		# in Makefile.in as well
++		if test ! -f "${srcdir}/$i" -a ! -f "${srcdir}/generic/$i" \
++		    -a ! -f "${srcdir}/win/$i" -a ! -f "${srcdir}/unix/$i" \
++		    ; then
++		    { { echo "$as_me:$LINENO: error: could not find source file '$i'" >&5
++echo "$as_me: error: could not find source file '$i'" >&2;}
++   { (exit 1); exit 1; }; }
++		fi
++		PKG_SOURCES="$PKG_SOURCES $i"
++		# this assumes it is in a VPATH dir
++		i=`basename $i`
++		# handle user calling this before or after TEA_SETUP_COMPILER
++		if test x"${OBJEXT}" != x ; then
++		    j="`echo $i | sed -e 's/\.[^.]*$//'`.${OBJEXT}"
++		else
++		    j="`echo $i | sed -e 's/\.[^.]*$//'`.\${OBJEXT}"
++		fi
++		PKG_OBJECTS="$PKG_OBJECTS $j"
++		;;
++	esac
++    done
++
++
++
++
+     vars="rs_ecc.c"
      for i in $vars; do
  	case $i in
-@@ -13653,5 +13653,5 @@
- 
- 
--    vars="md5-crypt/crypt-entry.c md5-crypt/md5-crypt.c md5-crypt/md5.c compat/stpncpy.c"
-+    vars="compat/stpncpy.c"
-     for i in $vars; do
- 	case $i in
-@@ -13713,5 +13713,5 @@
- 
- 
--    vars="md5-crypt/crypt-entry.c md5-crypt/md5-crypt.c md5-crypt/md5.c compat/stpncpy.c"
-+    vars="compat/stpncpy.c"
-     for i in $vars; do
- 	case $i in
+@@ -11047,7 +11083,7 @@
+ 	    UNSHARED_LIB_SUFFIX='${TCL_TRIM_DOTS}.a'
+ 	    TCL_LIB_VERSIONS_OK=nodots
+ 	    ;;
+-	NetBSD-*|FreeBSD-*)
++	NetBSD-*|MidnightBSD-*|FreeBSD-*)
+ 	    # FreeBSD 3.* and greater have ELF.
+ 	    # NetBSD 2.* has ELF and can use 'cc -shared' to build shared libs
+ 	    SHLIB_CFLAGS="-fPIC"
+@@ -11967,7 +12003,7 @@
+ 	    AIX-*) ;;
+ 	    BSD/OS*) ;;
+ 	    IRIX*) ;;
+-	    NetBSD-*|FreeBSD-*) ;;
++	    NetBSD-*|MidnightBSD-*|FreeBSD-*) ;;
+ 	    Darwin-*) ;;
+ 	    SCO_SV-3.2*) ;;
+ 	    *) SHLIB_CFLAGS="-fPIC" ;;
