refactor

diff --git a/mail/spamd/files/obspamlogd.in b/mail/spamd/files/obspamlogd.in
--- a/mail/spamd/files/obspamlogd.in
+++ b/mail/spamd/files/obspamlogd.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: ports/mail/spamd/files/obspamlogd.in,v 1.1 2007/06/06 16:38:53 miwi Exp $
+# $FreeBSD$
 #
 
 # PROVIDE: obspamlogd
@@ -15,22 +15,38 @@
 #
 # obspamlogd_enable="YES"	# Run the spamlogd(8) daemon (YES/NO).
 # obspamlogd_flags=""		# Extra flags for spamlogd(8) (if enabled).
+# obspamlogd_pflog_if=""	# pflog Interface for spamlogd(8) to monitor
 #
 # DO NOT CHANGE THESE DEFAULT VALUES HERE
 #
 obspamlogd_enable=${obspamlogd_enable:-"NO"}
-obspamlogd_flags=${obspamlogd_flags:-""}
 
-. %%RC_SUBR%%
+. /etc/rc.subr
 
 name="obspamlogd"
-rcvar=`set_rcvar`
+rcvar=obspamlogd_enable
 
 command="%%PREFIX%%/libexec/spamlogd"
-start_precmd="${name}_precmd"
+start_precmd="obspamlogd_precmd"
+stop_postcmd="obspamlogd_cleanup"
+pidfile="/var/run/spamlogd.pid"
 
 obspamlogd_precmd()
 {
+	if [ ! -z "${obspamlogd_pflog_if}" ]; then
+		# Configure i/f explicitly
+		load_kld pflog || {
+			warn "Unable to kldload pflog module"
+			return 1
+		}
+
+		if ! ifconfig ${obspamlogd_pflog_if} create up; then
+			warn "could not bring up ${obspamlogd_pflog_if}"
+			return 1
+		fi
+
+		rc_flags="${rc_flags} -l ${obspamlogd_pflog_if}"
+	fi
 	_rc=0
 	/sbin/mount -p | grep 'fdescfs.*/dev/fd.*fdescfs.*rw' 2>&1 > /dev/null
 	_rc=${?}
@@ -43,6 +59,14 @@ obspamlogd_precmd()
 		echo ""
 	fi
 	return ${_rc}
+}
+
+obspamlogd_cleanup()
+{
+	if [ -n "${obspamlogd_pflog_if}" ]; then
+	    ifconfig ${obspamlogd_pflog_if} destroy
+	fi
+	/bin/rm -f ${pidfile}
 }
 
 load_rc_config $name
