move dovecot

diff --git a/mail/dovecot/files/dovecot.in b/mail/dovecot/files/dovecot.in
--- a/mail/dovecot/files/dovecot.in
+++ b/mail/dovecot/files/dovecot.in
@@ -1,10 +1,11 @@
 #!/bin/sh
 #
-# $FreeBSD: head/mail/dovecot2/files/dovecot.in 422397 2016-09-18 16:38:28Z ohauer $
+# $FreeBSD: head/mail/dovecot/files/dovecot.in 483490 2018-10-30 14:04:21Z ler $
 #
 
 # PROVIDE: dovecot
 # REQUIRE: %%REQUIRE%%
+# BEFORE:  mail
 # KEYWORD: shutdown
 
 # dovecot_enable (bool):	Set it to YES to enable dovecot
@@ -38,16 +39,13 @@ restart_cmd="restart_cmd"
 extra_commands="reload"
 
 start_precmd()
-{	# Ensure runtime directories exist with correct permissions
-	local login_user login_gid
-	login_user=$(${command} ${command_args} -a | /usr/bin/awk -F '= ' '/^default_login_user =/ { print $2 }')
-	login_gid=$(/usr/sbin/pw usershow -n "${login_user}" 2>/dev/null | /usr/bin/cut -d: -f4)
+{	# Ensure runtime directory exists with correct permissions
 	/usr/bin/install -o root -g wheel -m 0755 -d ${base_dir}
 }
 
 stop_postcmd()
-{	# Cleanup runtime directories
-	rm -rf ${base_dir} 2>/dev/null
+{	# Cleanup runtime directory. The dovecot.conf link has to stay.
+	/usr/bin/find ${base_dir} ! -type l -delete
 }
 
 restart_cmd()
@@ -62,13 +60,21 @@ for config in ${dovecot_config}; do
 	required_files="${config}"
 	command_args="-c ${config}"
 	if [ -s ${config} ]; then
-		base_dir=$(${command} ${command_args} -a | /usr/bin/awk -F '= ' '/^base_dir =/ { print $2 }')
+               ${command} ${command_args} -a 2>&1 >/dev/null
+                if [ $? -ne 0 ]; then
+                       echo "==Error=="
+                       echo "Configuration file check failed."
+                       # Use dovecot to print the config error.
+                       ${command} ${command_args} -a
+                       exit $?
+                fi
+		base_dir=$(${command} ${command_args} -a 2>/dev/null | /usr/bin/awk -F '= ' '/^base_dir =/ { print $2 }')
 		pidfile="${base_dir}/master.pid"
 	else
 		echo "==Error=="
 		echo "Config file ${config} does not exist. If this is"
 		echo "a new installation, please create the config files as outlined in"
-		echo "	# pkg info -D dovecot2"
+		echo "	# pkg info -D dovecot"
 	fi
 	run_rc_command "$1"
 done
